services:
  simpletransferwebsite:
    image: simpletransferwebsite
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 10098:80
    volumes:
      - videos:/usr/local/apache2/htdocs/videos

volumes:
  videos: {}